import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SimpleFooter from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next Blog App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="bg-blue-gray-50/50">
				<Navbar />
				{children}
				<SimpleFooter />
			</body>
		</html>
	);
}
